### ISSUE TITLE
Erro ao tentar atualizar para da versão 3.0.3.1 para 3.0.3.2

### ISSUE THREAD

**Issue by adilsonb** [opencartbrasil/opencartbrasil#10]
Ao tentar atualizar da versão 3.0.3.1 para a 3.0.3.2 recebo a seguinte mensagem de erro:

> Baixando a última versão...
Internal Server Error
Internal Server Error
{"text":"Extraindo os arquivos...","next":"https:\/\/www.nomedosite.com.br\/loja\/admin\/index.php?route=tool\/update\/unzip&user_token=RS4aQZyUSOllg93FDh7qS3Oouyt5cj78"}: Error while sending QUERY packet. PID=3027 in  on line

Já aumentei os valores do " max_execution_time" e "max_allowed_packet_size" sem sucesso...

Alguma sugestão?

**Comment by v5manoel** [comment]
Pela mensagem de erro:
**Error while sending QUERY packet. PID=3027 in on line**

Fica claro que o problema continua sendo o serviço de banco de dados de sua hospedagem, neste caso, altere o valor de "**max_allowed_packet**" para **16777216** que corresponde a **16M**, e verifique se o problema será resolvido.

**Não esqueça que o servidor de banco de dados deve ser reiniciado após as alterações.**
