### ISSUE TITLE
[bug] Ao abrir um form em _blank retorna na mesma página 

### ISSUE THREAD

**Issue by redbraz** [opencartbrasil/opencartbrasil#102]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.7~
**Que parte da loja é afetada pelo erro?**
Um pequeno Bug na administração

**Faça um resumo do problema ocasionado pelo erro:**
Um pequeno Bug ocorre em forms que deveriam abrir em "_blank" porém abre na mesma página, eu corrigi o problema alterando o código do common.js do admin, 
Na linha 26 ~32 removi deixando apenas 

```
// Form Submit for IE Browser
	$('button[type=\'submit\']').on('click', function(e) {
		if ($("form[id*='form-']").length > 0) {
			e.preventDefault();
			$("form[id*='form-']").submit();
		}
	});
```
Deixando assim:
```
//Form Submit for IE Browser
	$('button[type=\'submit\']').on('click', function() {
		$("form[id*='form-']").submit();
	});

```
O erro foi mencionado no fórum:
https://forum.opencartbrasil.com.br/viewtopic.php?f=76&t=22387

**Comment by v5mvidal** [comment]
Perfeito! A correção estará na próxima versão.
