### ISSUE TITLE
Ordem errada do campo custom CPF ao Editar um cliente.

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#14]
**Em que versão do OpenCart Brasil o erro ocorre?**
R: 3.0.3.2 (1.4.1)

**Que parte da loja é afetada pelo erro?**
R: Na área administrativa, ir em Clientes -> Editar algum cadastro de cliente.
R: Na frente da loja, ir em Minha Conta -> Editar Informações da Conta.

**Faça um resumo do problema ocasionado pelo erro:**
R: A ordem do campo CPF está ficando entre o campo Nome e Sobrenome.

**Link para imagens com capturas da tela de erro:**
R: https://i.postimg.cc/9f7vYxCk/cpf.jpg
R: https://i.postimg.cc/x1C5KgKS/cpf2.jpg

**Comment by v5mvidal** [comment]
Obrigado por notificar o problema @rlasmar :)

**Comment by rlasmar** [comment]
O bug continua presente na versão 1.4.2 no front end da loja. Na parte admin foi corrigido.

![Capturar](https://user-images.githubusercontent.com/37814975/61179167-6d2b2900-a5cb-11e9-9769-6e865e34015f.JPG)

**Comment by v5mvidal** [comment]
Em que parte do frontend?

- No registro de conta dentro de minha conta.
- Na edição dos dados dentro de minha conta.
- No checkout na etapa de registro da conta.

Testei nos três locais e em nenhum deles o erro mencionado ocorre.

**Importante:** Não esqueça que na versão 3 do OpenCart você deve limpar o cache de modificações e do tema indo no menu **Extensões→Modificações** e clique no botão "**Atualizar**" (cor azul claro), para atualizar o cache de modificações, depois vá na página principal do painel de controle da administração da loja, abaixo do botão "**Sair**", você verá um botão na cor azul com o desenho de uma engrenagem branca dentro dele, clique neste botão, e no popup que vai abrir, clique nos dois botões na cor laranja que estão dentro da coluna "**Ação**" para atualizar o cache do tema.

Outro detalhe importante é que se você editou as páginas de cadastro da loja através do **Editor de Temas do OpenCart**, você deve excluir totalmente as alterações para que os arquivos atualizados do tema possam ser carregados, caso contrário não vai funcionar.

**Comment by rlasmar** [comment]
1. Limpei o cache das modificações
2. Limpei o cache do tema
3. Limpei o cache do navegador
4. Não há alteração peço Editor de Temas.

O bug está somente na parte **Na edição dos dados dentro de minha conta.**

**Comment by v5mvidal** [comment]
Corrigido. 😃
