### ISSUE TITLE
Erro de tradução "logged"

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#15]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 (1.4.1)

**Que parte da loja é afetada pelo erro?**
R: Administração da loja, área de atividades recentes

**Link para imagens com capturas da tela de erro:**
R: https://i.postimg.cc/50LWff0p/logged.jpg

**Comment by v5mvidal** [comment]
Obrigado por notificar o problema @rlasmar :)
