### ISSUE TITLE
Breadcrumb passando do layout no mobile quando titulo é grande.

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#16]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 (1.4.1)

**Que parte da loja é afetada pelo erro?**
Página do produto

**Faça um resumo do problema ocasionado pelo erro:**
O layout se estende além dos limites da página do produto, quando há um titulo grande no nome do produto na parte do breadcrumb.

**Link para imagens com capturas da tela de erro:**
https://i.postimg.cc/q7Q9S4qD/breadcrumb.jpg

**Comment by v5mvidal** [comment]
Obrigado por notificar o problema @rlasmar :)
