### ISSUE TITLE
Seleção de tipo de clientes não está funcionando

### ISSUE THREAD

**Issue by MillerSp** [opencartbrasil/opencartbrasil#17]
Tentei de varias formas mas não sei programar, a parte onde deveria aparecer os botoes de radio para escolher pessoa fisica ( que fica checkado) e pessoa juridica ( que abre o campo de cnpj e a inscrição estadual se for escolhido não funcionam ).

Na versao 2.3 se eu clicasse na pessoa juridica o cpf desaparecia e aparecia o cnpj, agora essa parte não funciona...

**Comment by v5mvidal** [comment]
Informe mais detalhes sobre o problema, e se possível faça um vídeo e publique no youtube para exemplificar o problema, pois no tema default (padrão) do OpenCart Brasil 3.0.3.2, este problema não ocorre.

**Comment by MillerSp** [comment]
Manoel, Obrigado pelo retorno, vou fazer  download agora da versao ( que é a mesma que fiz antes ). Desta vez vou fazer assim... Vou instalar em www.acrilinjet.com.br/loja a versao sem nenhuma modificação. Vou instalar a Modificação de Campos Personalizados e configurar ela e na sequencia vou transformar o Usuario PADRAO em PESSOA FISICA na sequencia criar um usuario chamado PESSOA JURIDICA.
Vou definir pessoa fisica aparecer obrigatorio e obrigatorio o preenchimento, e na sequencia também o PESSOA JURIDICA obrigatorio e obrigatorio na sequencia.
Vou criar antes o Número (id1) e Complemento (id2) e CPF (id3) CNPJ (id4) e INSCRIÇÃO ESTADUAL (id5) 
Faço os testes e depois te passo aqui se deu certo.
Importante: Existe alguma coisa estranha com o opencart nesta versao 3 ( uso o chrome para usa-lo e edita-lo no backend admin )...
--- Em algumas vezes a gravação dos dados não acontece como se houvesse algum problema em escrever ou gravar nas tabelas do banco de dados... 
--- Tem acontecido bastante ( uso a versao 2.3.0.2 em + 4 lojas e não acontece isso, nunca aconteceu, e nas 2 lojas 3.0.3.2 do opencart existe algum problema nessa parte.
.
Não sei programar, e estou aprendendo assistindo videos de youtube, mas vi que basicamente voce carrega o openart nas costas sozinho, gostaria de ajudar a melhor, poderia eu mudar alguns detalhes em alguns arquivos e enviar para voce aprovar e a gente deixar o opencart melhor ?
Se for o caso não faço nem questao de aparecer, mas acredito que possa ajudar
Vou fazer o teste agora da forma que lhe descrevi acima, daqui uns 30 minutos estará online em www.acrilinjet.com.br/loja
Obrigado pela paciencia, sou grato
Miller Simberg Anaia

**Comment by MillerSp** [comment]
Manoel, Boa Noite. O erro foi eu mesmo... Na aba de configurações da loja apos criar o tipo de cliente devria ter sido liberado como tipo de cliente valido, na aba configurações >>> opções
.
Sobre alguns detalhes eu poderia ajudar em alguma coisa? 
Se for o caso não precisa nem eu aparecer, se poder ajudar ja fico satisfeito.
Grato
Miller

**Comment by v5mvidal** [comment]
@MillerSp, boa noite.

Pode ajudar assim, teste bastante a versão Brasil, e em caso de erro de funcionamento, registre uma issue para cada erro separadamente, sempre relatando com detalhes o passo a passo de como o erro ocorreu e o que ele afeta, assim será possível simular a situação para confirmar se de fato é um erro, e providencia a correção e atualização da plataforma.

Obrigado por se dispor a ajudar. 😃
