### ISSUE TITLE
Uncaught TypeError: $(...).tooltip is not a function

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#18]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 (1.4.2)

**Que parte da loja é afetada pelo erro?**
Front end, várias partes da loja ocorre o erro que só pode ser visto no console do navegador, as vezes sim as vezes não, depende se já estiver em cache.

**Faça um resumo do problema ocasionado pelo erro:**
O problema ocorre no primeiro acesso da página em algumas funções, a página não carrega direito, mas ao atualizar a página, ele carrega normalmente, pois o arquivo já se encontra em cache.
Acredito que o erro se encontra no arquivo catalog/view/theme/default/template/common/header.twig
Código: <script src="catalog/view/javascript/bootstrap/js/bootstrap.min.js" type="text/javascript" **async**></script>
Ao retirar o async a loja passa a carregar normalmente no primeiro acesso sem erros.

**Link para imagens com capturas da tela de erro:**
https://i.postimg.cc/HxmGwP5t/erro.jpg

**Comment by v5mvidal** [comment]
Corrigido. 😃
