### ISSUE TITLE
[Sugestão] Filtro para pesquisar pedidos que possuam comentário

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#19]
Desculpa desde já se estou inserindo essa solicitação em local errado, não encontrei o local adequado para solicitar nova função.

Gostaria de solicitar um campo de **filtro/busca na área de pedidos, para localizar comentários inseridos nos históricos dos pedidos.**

![tempsnip](https://user-images.githubusercontent.com/37814975/62053768-459ca900-b1e6-11e9-87e9-d4b1bf627181.jpg)

**Comment by v5mvidal** [comment]
Olá @rlasmar.

Seria um filtro para localizar pedidos em que o cliente tenha preenchido o comentário?

**Comment by rlasmar** [comment]
Não, é um filtro para localizar pedidos em que o admin tenha inserido
comentários, deixei uma tela de exemplo abaixo onde fica esses comentários

[image: image.png]

Em seg, 29 de jul de 2019 às 09:54, Manoel Vidal <notifications@github.com>
escreveu:

**Comment by v5mvidal** [comment]
A tela de exemplo não está aparecendo.

**Comment by rlasmar** [comment]
Atualizei o comentário acima.

**Comment by v5mvidal** [comment]
É um filtro para pesquisar os comentários no histórico dos pedidos.

Vou analisar com calma qual o impacto deste filtro, pois por se tratar de um resultado que pode retornar muitos dados, pois sempre haverá mais históricos que pedidos, podemos ter problemas no banco de dados uma vez que a consulta será feita em um campo do tipo text que possui pouca otimização, principalmente se o cliente tiver instalado extensões com modificações no comentário, então todo cuidado é pouco para não provocar crash no banco de dados. :)

**Comment by rlasmar** [comment]
Beleza!

Aproveitando esta função, lembrei que de vez em quando alguns clientes se cadastram com o e-mail errado, portanto ao realizar o pedido eles não anotam o número do pedido e não recebem o e-mail com número do pedido e depois para localizar o pedido fica ruim.

Então, se possível inserir um filtro para localizar pedidos por CPF, Telefone, CEP e E-mail diretamente na página de pedidos no admin. Para poupar espaço de campos, poderia inserir somente um campo e neste campo ser possível buscar por todas essas variáveis.

**Comment by v5mvidal** [comment]
Acredito que um filtro pelo e-mail registrado no pedido seria mais que o suficiente para a situação que você relatou, pois quanto mais variáveis de filtro, mais lenta ficará a consulta e mais dados serão retornados, e isso pode aumentar os casos de crash no banco de dados, pois infelizmente a maioria dos lojistas utiliza o OpenCart em hospedagens de péssima qualidade.

**Comment by rlasmar** [comment]
Mas ocorre que tem clientes que simplesmente colocam e-mail errado, erro de grafia mesmo. Por exemplo: @hotmai.com @gmal.com esses tipos de erros, aí não daria para localizar.

Talvez então para localizar por e-mail e por CEP do endereço de entrega, apenas 2 varáveis.

**Comment by v5mvidal** [comment]
Neste caso você teria que pesquisar pelo e-mail errado, e não pelo e-mail correto, ou pesquisar por partes do e-mail e não o e-mail completo, tipo '**fulano@**', pois como citei, não adianta colocar muitos filtros e sobrecarregar o banco de dados com uma consulta, pois se fizermos isso, passaremos a ter vários relatos de problemas de crash no banco de dados, e lojistas reclamando que o OpenCart não presta. ;)

**Comment by v5mvidal** [comment]
Se a maioria dos lojistas utilizasse o OpenCart em ambientes isolados e com recursos dedicados para OpenCart, poderíamos ter filtros de todos os tipos, porém, de longe essa é a realidade, então não adianta ignorar o fator hospedagem ruim, e ir adicionando filtros que sem dúvidas isso causará problemas e reclamações. ;)

**Comment by MillerSp** [comment]
Olá, Manoel,
Olá RLasmar,
Desculpe me intrometer, mas essa busca seria muito util por cpf ou cnpj ao meu ver, porque seria pouco usada, eu tive um caso aqui que deu trabalho achar o cadastro da cliente porque nao aceitava o mesmo cpf para um novo cadastro e o email nao recuperava senha porque dava que não existia, no fim das contas a cliente usou outro email para cadastro e ainda errou o mesmo ( essas coisas acontecem toda hora ) e depois ainda achava que a gente era culpado aí eu tive que achar na unha o cadastro da cliente enquanto ela falava pra mim que minha loja era sem confiança etc etc etc....
...
Pergunta: 
Sera que não seria melhor substituir a busca por IP por busca por CPF ou CNPJ ?

Eu uso a modificação de mascara do periscuelo e uso cpf e cnpj separados como campos adicionais, isso atrapalharia ?
Boa tarde a todos

**Comment by v5mvidal** [comment]
@MillerSp A busca por IP é uma consulta simples que não sobrecarrega as consultas de pedidos e clientes, porém, a busca por campos personalizados como CPF ou CNPJ seria uma busca complexa, que demandaria mais recursos da hospedagem dependendo da quantidade de cadastrados de pedidos ou clientes.

Como citei na última mensagem, atualmente não dá para incluir filtros complexos, quando a maioria dos lojistas tem grandes quantidades de dados em hospedagens de péssima qualidade.

Neste caso seria mais fácil instalar na loja uma modificação que habilite este filtro, assim se causar problemas é só desinstalar.

**Comment by v5mvidal** [comment]
@rlasmar vou adicionar um filtro simples com a funcionalidade de pesquisar pedidos com comentários preenchidos, assim não vai sobrecarregar a consulta e ajudará a resolver a demanda de identificar pedidos com comentários.

**Comment by rlasmar** [comment]
Obrigado, aguardo pela novidade.

**Comment by v5mvidal** [comment]
Feito. =)
