### ISSUE TITLE
[bug] Campo Bairro não aparece ao Editar endereço do cliente no Admin

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#21]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 (1.4.3)

**Que parte da loja é afetada pelo erro?**
Admin -> Clientes -> Editar Cliente -> Endereço

**Faça um resumo do problema ocasionado pelo erro:**
O campo bairro não aparece para editar. Ele deveria ficar antes do campo Cidade.

**Link para imagens com capturas da tela de erro:**
![Bairro](https://user-images.githubusercontent.com/37814975/62390786-1ad98a00-b531-11e9-9dda-efb36513229d.JPG)

**Comment by v5mvidal** [comment]
Aqui está aparecendo normalmente o campo bairro ao editar o cliente, ou ao cadastrar um novo cliente através da administração da loja na versão 3.0.3.2 (Brasil 1.4.3).

O problema ainda continua?
Alguma modificação instalada na loja pode está causando o problema?

**Comment by rlasmar** [comment]
Desculpe-me, era uma modificação mesmo. Acabei de encontrar a extensão que causava este problema.
