### ISSUE TITLE
[bug] Botão de Editar na lista de pedidos não funciona no celular.

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#22]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 (1.4.3)

**Que parte da loja é afetada pelo erro?**
Lista de Pedidos no Admin Mobile - Clicar para editar algum pedido

**Faça um resumo do problema ocasionado pelo erro:**
No celular ir até a lista de pedidos, ao clicar para editar o pedido, na seta que fica ao lado do olho (exibir), fica impossível deslizar para o lado para poder clicar em Editar.

**Comment by v5mvidal** [comment]
Corrigido.
