### ISSUE TITLE
[bug] Contagem de informativos enviados errada

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#25]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 (1.4.3)

**Que parte da loja é afetada pelo erro?**
No admin - Marketing - Informativo

**Faça um resumo do problema ocasionado pelo erro:**
Ao enviar e-mails para os clientes, informa quantidade 0 de clientes, mesmo enviando o e-mail

**Link para imagens com capturas da tela de erro:**
![Capturar](https://user-images.githubusercontent.com/37814975/63116893-b4109380-bf68-11e9-9207-44a260869ac9.JPG)

**Comment by v5mvidal** [comment]
@rlasmar você poderia informar como preencheu o campo "**Para**" do informativo?

**Comment by v5mvidal** [comment]
Corrigido.
