### ISSUE TITLE
Ajustes e Melhorias para Tabela oc-session

### ISSUE THREAD

**Issue by MillerSp** [opencartbrasil/opencartbrasil#27]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 versao 1.4.3

**Que parte da loja é afetada pelo erro?**
Banco de Dados

**Faça um resumo do problema ocasionado pelo erro:**
A loja acumula sessoes mesmo que o admin esteja logado e usando o admin da loja, apaguei a tabela oc_session e depois entrei no admin usando login e senha e depois de uns 3 minutos mesmo sem fazer nada estava com mais de 6 sessoes na tabela do banco de dados,
porém isso não é tudo,
A loja estava com mais de 670.000 sessoes no banco de dados
Seria interessante colocar no admin um periodo para auto deletar as sessoes de entrada ( para 5 dias por exemplo, porque a rotina de compra do cliente já estaria de uma forma geral completa...

**Link para imagens com capturas da tela de erro:**

**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

 - Você está em um computador local ou hospedagem web?
Uso uma hospedagem cloud bluehost

 - Se estiver em uma hospedagem web, qual hospedagem?
 bluehost cloud

 - Qual o sistema operacional utilizado?
 linux

 - Qual o servidor web utilizado?
acredito que apache
 
 - Qual o servidor de banco dados utilizado?
phpmyadmin
 
 - Qual a versão do PHP?
7.0
 
 - Se aplicável, qual o(s) navegador(es) utilizado(s) [por exemplo: chrome 75]:
google chrome
 
 - Se aplicável, informe detalhes do dispositivo móvel utilizado:

Estive lendo sobre isso no seguinte link https://forum.opencart.com/viewtopic.php?t=205907

Desculpe se foi incomodo, grato
Miller Simberg Anaia

**Comment by v5mvidal** [comment]
Olá @MillerSp 

Adicionei informações sobre as tarefas agendadas, que são responsáveis por higienizar de forma automática as sessões de login, além de atualizar a cotação das moedas, segue:
https://github.com/opencartbrasil/opencartbrasil/blob/master/README.md#habilitar-as-tarefas-agendadas

**Comment by MillerSp** [comment]
Olá
Manoel
Obrigado pela atenção, vou estudar essa parte esse fim de semana
Fico grato pela atenção, sobre o sitemap eu passo pelo email depois
Grato
Miller Simberg Anaia

Em sáb, 12 de out de 2019 12:58, Manoel Vidal <notifications@github.com>
escreveu:
