### ISSUE TITLE
[bug] Sitemap rejeitado pelo Google

### ISSUE THREAD

**Issue by MillerSp** [opencartbrasil/opencartbrasil#28]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.2 versao 1.4.3

**Que parte da loja é afetada pelo erro?**
afeta o rankeamento do google

**Faça um resumo do problema ocasionado pelo erro:**
na minha conta do glogle esta aparecendo a informação de que a formatação xml do sitemap está errada, observei que a versao 2.1.0.2 que tenho uma loja abre o xml normalmente, já na 3.x o erro não deixa aparecer adequadamente ( e quando é acessado direto o xml tenta abrir e na sequencia ja fecha e aparece os links sem o xml ) 
Troquei a versao que eu tinha da 2.1.0.2 e depois disso venho perdendo relevancia no google e o google ja me notificou varias vezes sobre isso, porém tentei varias formas de ajustar 

**Link para imagens com capturas da tela de erro:**

**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

 - Você está em um computador local ou hospedagem web?
 hospedagem
 - Se estiver em uma hospedagem web, qual hospedagem?
 bluehost, cloud

 - Qual o sistema operacional utilizado?
 windows 10

 - Qual o servidor web utilizado?
 linux
 - Qual o servidor de banco dados utilizado?
 apache
 - Qual a versão do PHP?
 7.0
 - Se aplicável, qual o(s) navegador(es) utilizado(s) [por exemplo: chrome 75]:
 chrome
 - Se aplicável, informe detalhes do dispositivo móvel utilizado:

**Comment by v5mvidal** [comment]
Olá @MillerSp 

Informe o link do seu Sitemap para que seja possível analisá-lo e identificar o problema.

**Comment by v5mvidal** [comment]
Olá @MillerSp.

Você poderia informar o link do sitemap da sua loja para analisarmos  o problema?

**Comment by MillerSp** [comment]
Oi Manoel

Desculpe-me não enviar antes o link

So pude ver isso agora

Segue o link do sitemap

https://www.brindesbarato.com.br/sitemap.xml

Aparece esta mensagem:
This XML file does not appear to have any style information associated with
it. The document tree is shown below.

grato

Miller Simberg Anaia

Em qui, 17 de out de 2019 às 08:46, Manoel Vidal <notifications@github.com>
escreveu:

**Comment by MillerSp** [comment]
Manoel
Vi também que no w3c.org existem alguns problemas

Abteriormente eu havia retirado as instruções para deixar sem erros mas ao
atualizar a loja os eros voltaram

Segue o link

https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.brindesbarato.com.br%2F

Grato

Miller Simberg Anaia

Em sáb, 19 de out de 2019 às 20:14, M-FTC SP <miller.ftc@gmail.com>
escreveu:

**Comment by v5mvidal** [comment]
@MillerSp, analisei seu sitemap.xml e não há nenhum problema com ele, passei também por uma ferramenta de validação, e novamente nenhum problema foi encontrado, segue uma das ferramentas utilizadas para análise:
https://www.xml-sitemaps.com/validate-xml-sitemap.html

Poderia verificar?

**Comment by v5mvidal** [comment]
Sobre a validação que você fez no w3c.org, veja que não são problemas, são avisos, ou seja, seu tema funcionará normalmente e sem erros, e isso em nada impactará a avaliação dos mecanismos de busca em sua loja.

Em resumo, **não é um bug**, e caso lhe incomode visualizar os avisos na validação, basta editar o arquivo:
catalog/view/theme/PASTA_DO_SEU_TEMA/template/common/**header.twig**

E alterar a linha abaixo:
`<script src="{{ script }}" type="text/javascript"></script>`

Para:
`<script src="{{ script }}"></script>`

Por último, vá no menu **Extensões→Modificações** e clique no botão "**Atualizar**" (cor azul claro), para atualizar o cache de modificações, depois vá na página principal do painel de controle da administração da loja, abaixo do botão "**Sair**", você verá um botão na cor azul com o desenho de uma engrenagem branca dentro dele, clique neste botão, e no popup que vai abrir, clique nos dois botões na cor laranja que estão dentro da coluna "**Ação**" para atualizar o cache do tema.
