### ISSUE TITLE
[bug] Erro na home após atualizar para 1.4.4

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#31]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.4.4

**Que parte da loja é afetada pelo erro?**

Home principal
Nas categorias o site abre normal.

**Faça um resumo do problema ocasionado pelo erro:**

Exception: Erro: Table 'admin_copia.oc_product p' doesn't exist

Código: 1146
SELECT p.product_id, (SELECT AVG(rating) AS total FROM `oc_review` r1 WHERE r1.product_id = p.product_id AND r1.status = '1' GROUP BY r1.product_id) AS rating, (SELECT price FROM `oc_product_discount` pd2 WHERE pd2.product_id = p.product_id AND pd2.customer_group_id = '1' AND pd2.quantity = '1' AND ((pd2.date_start = '0000-00-00' OR pd2.date_start < NOW()) AND (pd2.date_end = '0000-00-00' OR pd2.date_end > NOW())) ORDER BY pd2.priority ASC, pd2.price ASC LIMIT 1) AS discount, (SELECT price FROM `oc_product_special` ps WHERE ps.product_id = p.product_id AND ps.customer_group_id = '1' AND ((ps.date_start = '0000-00-00' OR ps.date_start < NOW()) AND (ps.date_end = '0000-00-00' OR ps.date_end > NOW())) ORDER BY ps.priority ASC, ps.price ASC LIMIT 1) AS special FROM `oc_product p` LEFT JOIN `oc_product_description` pd ON (p.product_id = pd.product_id) LEFT JOIN `oc_product_to_store` p2s ON (p.product_id = p2s.product_id) WHERE pd.language_id = '2' AND p.status = '1' AND p.date_available <= NOW() AND p2s.store_id = '0' GROUP BY p.product_id ORDER BY p.date_added DESC, LCASE(pd.name) DESC LIMIT 0,4

**Comment by rlasmar** [comment]
O que já fiz até o momento para tentar identificar o problema:

1. Fui em modificações e cliquei no botão laranja para desabilitar todas as extensões.
2. Limpei o cache twig

O erro persiste.

**Comment by rlasmar** [comment]
Após mais alguns testes, desativei o modulo nativo Produtos Novos que já vem no proprio opencart, e o problema está nele. Quando ele está ativado ocorre o erro da tabela acima citado.

Houve alguma modificação no modulo Produtos Novos?

**Comment by v5mvidal** [comment]
Atualize sua versão novamente, pois reenviei os pacotes da instalação com o bug corrigido. =)
