### ISSUE TITLE
Barra de rolagem as vezes funciona e as vezes não funciona.

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#35]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.4.8

**Que parte da loja é afetada pelo erro?**
Admin

**Faça um resumo do problema ocasionado pelo erro:**
A barra de rolagem muitas vezes some, ou fica cinza sem poder rolar. Neste caso, só funciona pelo scroll do mouse.

Em outras vezes funciona normal.

Acontece este problema Google Chrome 79.
No Firefox funciona normal.

**Link para imagens com capturas da tela de erro:**
No caso da imagem, ela está cinza, mas sem poder rolar, está travada. 

![Capturar](https://user-images.githubusercontent.com/37814975/72104063-f0220780-3300-11ea-8f10-7dd1e8f70ebc.JPG)

**Comment by v5mvidal** [comment]
Olá @rlasmar.

Qual o sistema operacional utilizado?

Qual a dimensão em pixel da sua tela?

**Comment by rlasmar** [comment]
Windows 10

Resolução: monitor ultrawide 2560 x 1080

Por ser um monitor grande, uso a escala de zoom do Google Chrome em 125%
para não ficar pequeno demais as letras.

Em sáb, 11 de jan de 2020 10:35, Manoel Vidal <notifications@github.com>
escreveu:

**Comment by v5mvidal** [comment]
Desative o zoom no Google Chrome, e limpe o cache do navegador, depois teste se sem o zoom o problema ocorre, e dê um feedback. :)

**Comment by v5mvidal** [comment]
Fechado por falta de feedback.
