### ISSUE TITLE
[bug] Problema com campos extras na view do tema (catalog)

### ISSUE THREAD

**Issue by FelipoAntonoff** [opencartbrasil/opencartbrasil#38]
Olá, segue abaixo algumas informações sobre o problema.

**Em que versão do OpenCart Brasil o erro ocorre?**
Versão Versão 3.0.3.2 (Brasil 1.4.10)

**Que parte da loja é afetada pelo erro?**
Minha conta -> Informação da conta e Minha Conta -> Endereços -> Editando endereço do Cliente

**Faça um resumo do problema ocasionado pelo erro:**
No Editar os dados do cliente, está sem exibir os campos extras do cliente.
Já no editar o endereço os campos extras ficaram fora da ordem padrão

**Resolução**
Consegui resolver para o cliente, colocando o arquivo nativo do 3.0.3.2, o edit.twig e o address_form.twig que ficam na pasta catalog/view/theme/default/template/account/ .

Acredito ser algum detalhe ligado a JS.

O cliente só instalou a Loja e o xml Export/Import Tool, deixei desativado no teste as Modificações.

**Comment by v5mvidal** [comment]
Olá @FelipoAntonoff.

O problema não foi confirmado em nosso ambiente de teste da versão citada, porém, não o descartamos, mas neste caso, você poderia fazer uma instalação limpa do OpenCart Brasil e verificar se o problema de fato ocorre, sendo que já encontramos instalações da versão Brasil com erros causados por instalações de temas que alteram arquivos padrões do OpenCart Brasil.

**Comment by FelipoAntonoff** [comment]
Olá, @v5mvidal, no caso a loja foi instalada do zero pelo cliente e sem uso de outro tema.
Verificamos também os arquivos com o do github e está igual.

Após instalado foi criado os campos extras: CPF, Número, Complemento e Data de Nascimento.
No Cadastro e no Checkout ficaram normal, já no editar do cliente estava sem eles e no editar endereço com ordem errada.

Quando voltei os arquivos da view para os nativos, voltou ao normal.
O cliente usa o tema nativo, na instalação dele tem o nativo e o default, ele usou o default.

A loja pelo que vi usa a hospedagem da OVH, não sei se poderia ter alguma relação, mas creio que não, já que normalizou depois que trocamos os arquivos.

Testei no Google Chrome 80.0.3987.149.

**Comment by v5mvidal** [comment]
Se for possível, faça uma instalação nova da versão Brasil, assim teríamos mais uma análise, pois realizamos 5 testes em ambientes diferentes que possuímos, e não conseguimos reproduzir o problema, por seria importante ter seu feedback.

**Comment by v5mvidal** [comment]
Fechado por falta de feedback.
