### ISSUE TITLE
[bug] Atenção: Você não tem permissão para acessar a API

### ISSUE THREAD

**Issue by cwblover** [opencartbrasil/opencartbrasil#39]
**Em que versão do OpenCart Brasil o erro ocorre?**
Versão 3.0.3.2 (Brasil 1.4.10) - registrado em versões anteriores.

**Que parte da loja é afetada pelo erro?**
Principal > Pedidos

**Faça um resumo do problema ocasionado pelo erro:**
Ao tentar Editar o pedido recebido pela loja aparece a mensagem: 
Atenção: Você não tem permissão para acessar a API.

**Link para imagens com capturas da tela de erro:**

https://i.pinimg.com/originals/fa/28/f4/fa28f41d519505456b0c728eabbc9880.jpg

**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

 - Você está em um computador local ou hospedagem web?
 Hospedagem Web 
 - Se estiver em uma hospedagem web, qual hospedagem?
 Godaddy
 - Qual o sistema operacional utilizado?
 Linux
 - Qual o servidor web utilizado?
 Cpainel + Apache 
 - Qual o servidor de banco dados utilizado?
 Mysql
 - Qual a versão do PHP?
 7.2
 - Se aplicável, qual o(s) navegador(es) utilizado(s) [por exemplo: chrome 75]:
Chrome 
Firefox

**Comment by v5mvidal** [comment]
Olá @cwblover.

Não é um bug, mas uma mensagem informando que você deve adicionar o seu IP nas configurações da API, sendo que geralmente quando você acessa a listagem de pedidos ou visualizar os detalhes do pedido, já é exibida no alto da página a mensagem que você deve adicionar o IP para poder editar o pedido acompanhada de um botão para você clicar e adicionar o IP, assim a mensagem só aparecerá novamente caso seu IP mude.

**Comment by cwblover** [comment]
@v5mvidal Obrigado pela resposta, mas ja foi adicionado o Ip conforme sugerido, e mesmo assim a mensagem aparece, e não me permite alterar o status do Pedido, ja fiz isso de mais de um cenario diferente e todos com o IP adicionado na lista de API e mesmo assim aparece essa mensagem.

**Comment by v5mvidal** [comment]
Você teria como testar com outro acesso a internet?
Pois gostaria de tirar a dúvida se o problema está sendo causado pela rápida mudança de IP em sua internet atual.

**Comment by cwblover** [comment]
Tenho como testar sim em outro acesso a internet, mas gostaria de acrescentar como exemplo que: desde ontem o meu IP é o mesmo, e mesmo adicionado a lista de IP Permitidos na API ele continua a apresentar a mesma mensagem. já havia realizado este teste (inclusive de acessos com o IP estático) e mensagem persistia. 
Alem disso, quando uso a opção de editar o pedido, parece a mesma mensagem mas no campo MOEDA.  Segue print:
[https://i.pinimg.com/originals/d9/5c/12/d95c120ec7bdfcf42d8e611c24626311.jpg](url).

**Comment by v5mvidal** [comment]
Tente gerar um nova API através da administração da loja no menu **Gerenciar usuário > API**, depois selecione a nova API nas configurações da loja no menu **Configurações > Gerenciar lojas**, edite a loja, localize o campo "**API da administração**", selecione a nova API e clique no botão **Salvar**.

**Comment by cwblover** [comment]
Conforme suas ultimas orientações, eu efetuei o teste e deu certo. Muito obrigado pela atenção. Chamado encerrado.

**Comment by MarcosLealDev** [comment]
Tive exatamente o mesmo problema quando eu editei  'redis' na versão 3.0.3.3 (Brasil 1.7.2) , php 7.4

Meu redis tem a seguinte configuração:
Adicionado ao config.php  
```php
define('CACHE_HOSTNAME', '127.0.0.1');
define('CACHE_PORT', '6379');
define('CACHE_PREFIX', 'redis_');
define('CACHE_EXPIRE', 3600);
``` 

Editei o system/config/default.php
```php
$_['cache_engine'] = 'redis';
$_['session_engine'] = 'redis';
```

Editei system/config/catalog.php
```php
$_['session_engine'] = 'redis';
``` 


Admin continua dizendo "Atenção: Você não tem permissão para acessar a API" quando eu tento editar o pedido.
Mas o cliente consegue comprar e utilizar o website sem problemas.

Retirando o redis, tudo funciona.
