### ISSUE TITLE
[bug] Openbay plugins edit errors - 3.0.3.2

### ISSUE THREAD

**Issue by condor2** [opencartbrasil/opencartbrasil#40]
You have many errors when try to edit installed plugins from Openbay:

- Notice: Trying to get property 'ebay' of non-object in admin/controller/extension/openbay/ebay.php on line 60 Error: Call to a member function validate() on null no arquivo
- Notice: Trying to get property 'etsy' of non-object in admin/controller/extension/openbay/etsy.php on line 69 Error: Call to a member function validate() on null no arquivo 
- Notice: Trying to get property 'amazon' of non-object in admin/controller/extension/openbay/amazon.php on line 61 Error: Call to a member function validate() on null no arquivo 
- Notice: Trying to get property 'amazonus' of non-object in admin/controller/extension/openbay/amazonus.php on line 60Error: Call to a member function validate() on null no arquivo
- Notice: Trying to get property 'fba' of non-object in admin/controller/extension/openbay/fba.php on line 59Error: Call to a member function validate() on null no arquivo

Another error when you click on Manage items

-Error: Call to a member function addonLoad() on null no arquivo admin/controller/marketplace/openbay.php na linha 1305

`14-05-2020 11:25:29 - Error:  Call to a member function testDbTable() on null no arquivo /admin/model/extension/openbay/openbay.php na linha 315
14-05-2020 11:25:39 - PHP Notice:  Trying to get property 'amazon' of non-object in /admin/controller/extension/openbay/amazon.php on line 61
14-05-2020 11:25:39 - Error:  Call to a member function validate() on null no arquivo /admin/controller/extension/openbay/amazon.php na linha 61
14-05-2020 11:25:54 - PHP Notice:  Trying to get property 'ebay' of non-object in /admin/controller/extension/openbay/ebay.php on line 60
14-05-2020 11:25:54 - Error:  Call to a member function validate() on null no arquivo /admin/controller/extension/openbay/ebay.php na linha 60
14-05-2020 11:29:47 - PHP Notice:  Trying to get property 'etsy' of non-object in /admin/controller/extension/openbay/etsy.php on line 69
14-05-2020 11:29:47 - Error:  Call to a member function validate() on null no arquivo /admin/controller/extension/openbay/etsy.php na linha 69
14-05-2020 11:30:09 - PHP Notice:  Trying to get property 'fba' of non-object in /admin/controller/extension/openbay/fba.php on line 59
14-05-2020 11:30:09 - Error:  Call to a member function validate() on null no arquivo /admin/controller/extension/openbay/fba.php na linha 59
14-05-2020 11:32:51 - Error:  Call to a member function addonLoad() on null no arquivo /admin/controller/marketplace/openbay.php na linha 1305
14-05-2020 11:35:39 - PHP Notice:  Trying to get property 'amazonus' of non-object in /admin/controller/extension/openbay/amazonus.php on line 60
14-05-2020 11:35:39 - Error:  Call to a member function validate() on null no arquivo /admin/controller/extension/openbay/amazonus.php na linha 60
14-05-2020 11:38:12 - Error:  Call to a member function testDbTable() on null no arquivo /admin/model/extension/openbay/openbay.php na linha 315`

Php 7.4

**Comment by v5mvidal** [comment]
Test with PHP 7.1 to 7.3

This module may not be compatible with PHP 7.4

**Comment by condor2** [comment]
Same issue with php 7.1.
