### ISSUE TITLE
[bug] Customer login error - 3.0.3.2

### ISSUE THREAD

**Issue by condor2** [opencartbrasil/opencartbrasil#43]
- Error when a customer login in his account
`Notice: Trying to access array offset on value of type bool no arquivo catalog/controller/startup/startup.php na linha 159`

When a customer  try to add address
![Screenshot_2020-05-16_10-25-20](https://user-images.githubusercontent.com/14251939/82113581-c7eb5f00-975f-11ea-939f-8a86e02904b7.png)

- PHP: 7.4
- Tested on Chromium 81, Firefox 76

**Comment by v5mvidal** [comment]
I was unable to replicate the error.

Have you tested it several times?
Are you using the default theme?

**Comment by condor2** [comment]
Yes.
Theme used is Default.
