### ISSUE TITLE
[Bug] PHP Warning:  filesize(): stat failed

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#47]
**Em que versão do OpenCart Brasil o erro ocorre?**

OC 3.0.3.3 (1.4.13)

**Que parte da loja é afetada pelo erro?**

Log de erros do admin

**Faça um resumo do problema ocasionado pelo erro:**
Não sei se ocorre algum erro na frente da loja, não sei nem como reproduzir este erro, mas após atualizar para a última versão 1.4.13, tem aparecido este erro diariamente no log.

PHP Warning:  filesize(): stat failed for /home/admin/web/dominio/public_html/system/storage/cache/cache.product.bestseller.2.0.1.150.1591648805 no arquivo /home/admin/web/dominio/public_html/system/library/cache/file.php na linha 32

**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

 - Você está em um computador local ou hospedagem web?
web
 
 - Se estiver em uma hospedagem web, qual hospedagem?
 
 - Qual o sistema operacional utilizado?
linux
 
 - Qual o servidor web utilizado?
apache
 
 - Qual o servidor de banco dados utilizado?
mysql
 
 - Qual a versão do PHP?
7.3

**Comment by v5mvidal** [comment]
Corrigido!
https://github.com/opencartbrasil/opencartbrasil/commit/d9afd93763209769a61f2f79a6ff7c552da90954

**Comment by rlasmar** [comment]
Atualizei para a versão 1.4.14, mas o erro ainda aparece.

17-06-2020 10:20:02 - PHP Warning:  fopen(/home/admin/web/dominio/public_html/system/storage/cache/cache.product.bestseller.2.0.1.150.1592407190): failed to open stream: No such file or directory no arquivo /home/admin/web/dominio/public_html/system/library/cache/file.php na linha 31
17-06-2020 10:20:02 - PHP Warning:  flock() expects parameter 1 to be resource, bool given no arquivo /home/admin/web/dominio/public_html/system/library/cache/file.php na linha 33
17-06-2020 10:20:02 - PHP Warning:  fread() expects parameter 1 to be resource, bool given no arquivo /home/admin/web/dominio/public_html/system/library/cache/file.php na linha 38
17-06-2020 10:20:02 - PHP Warning:  flock() expects parameter 1 to be resource, bool given no arquivo /home/admin/web/dominio/public_html/system/library/cache/file.php na linha 43
17-06-2020 10:20:02 - PHP Warning:  fclose() expects parameter 1 to be resource, bool given no arquivo /home/admin/web/dominio/public_html/system/library/cache/file.php na linha 45

**Comment by v5mvidal** [comment]
Adicionei uma nova melhoria para tratar estes erros:
https://github.com/opencartbrasil/opencartbrasil/commit/75816a5609e7e9b7a0e69204b36752f1541e4811

**Comment by rlasmar** [comment]
Novamente o erro ocorreu. Versão 1.4.15.
Você conseguiu reproduzir este erro?
Porque aqui passou uns 2 dias sem aparecer o erro e agora apareceu novamente no log.

 PHP Warning:  filesize(): stat failed for /home/admin/web/capascelular.net/public_html/system/storage/cache/cache.product.bestseller.2.0.1.150.1593267084 no arquivo /home/admin/web/capascelular.net/public_html/system/library/cache/file.php na linha 35

**Comment by v5mvidal** [comment]
Você recebe uma média de quantas visitas diárias?

Você poderia me informar como está configurada a diretiva "**realpath_cache_size**" no seu **php.ini**?

Preciso dessas informações para entender o cenário dos arquivos de cache em sua hospedagem.

**Comment by rlasmar** [comment]
Chequei o arquivo php.ini e a linha está comentada. Tenho recebido média de 2.800 visitas por dia

Note: if open_basedir is set, the cache is disabled
;realpath_cache_size = 4096k

No caso, meu open base dir está configurado assim:
php_admin_value open_basedir /home/admin/web/capascelular.net/public_html:/home/admin/tmp

**Comment by rlasmar** [comment]
Vc acha que algum modulo poderia estar causando este erro, mesmo não indicando o caminho modification na linha de erro?

**Comment by v5mvidal** [comment]
Não creio que algum módulo esteja causando o problema.

Mas acredito que o tempo de vida dos arquivos de cache possa ser pequeno ou por algum motivo ele não consiga ser lido por estar travado em outra leitura.

É provável que parte do erro tenha sido resolvido na última atualização pelo código se certificar que o arquivo de cache existe antes de prosseguir com a leitura dele, mas depois disso, pode ser que o arquivo de cache seja apagado pelo processo que valida o tempo de expiração do arquivo de cache, ou como citei, ele pode está travado em outra leitura (o que não era para acontecer), mas tudo é possível dependendo da configuração do PHP na hospedagem e levando em conta que esses processos ocorrem em milésimos de segundos.

Em todo caso, devemos tratar ambas as situações de modo a lidar com elas sem gerar o erro mencionado.

Vou fazer mais alguns testes aqui para preparar uma nova atualização de modo que possamos resolver o problema.

**Comment by rlasmar** [comment]
Manoel,

Eu não uso o modulo bestseller na minha loja. Eu achei que usava, mas não estava habilitado.
Eu fiz o seguinte, habilitei o modulo agora na loja, mas não coloquei no layout, assim ele não aparece na frente da loja.
Tem uns 4 dias que fiz isso, o erro ainda não apareceu.
Não sei se é coincidência, ou se esta foi a solução.

**Comment by rlasmar** [comment]
Atualizando o que disse acima, não resolveu não. O erro voltou a aparecer.

`PHP Warning:  filesize(): stat failed for /home/admin/web/capascelular.net/public_html/system/storage/cache/cache.product.bestseller.2.0.1.150.1594344325 no arquivo /home/admin/web/capascelular.net/public_html/system/library/cache/file.php na linha 35`

**Comment by v5mvidal** [comment]
Fiz uma melhoria na leitura do arquivo de cache, segue:
https://github.com/opencartbrasil/opencartbrasil/commit/7cb91fc387833b05ab123d5cef9c271aafaae7fc

Se for possível, copie o conteúdo do arquivo abaixo e substitua ele em sua loja para verificarmos se o problema será resolvido.

Segue o conteúdo do arquivo **file.php** atualizado:
https://raw.githubusercontent.com/opencartbrasil/opencartbrasil/master/system/library/cache/file.php

Em seu OpenCart você o encontrará no caminho abaixo:
system/library/cache/**file.php**

Aguardo retorno. 👍

**Comment by rlasmar** [comment]
Arquivo atualizado.
Qualquer erro que aparecer, volto aqui pra relatar.

**Comment by v5mvidal** [comment]
Vou fechar a issue até você informar seu feedback. 👍

**Comment by rlasmar** [comment]
Acredito que tenha resolvido. Já são 12 dias sem o erro.

**Comment by v5mvidal** [comment]
Show! Então na próxima versão já estará incluído. :)
