### ISSUE TITLE
PHP Notice:  Undefined index: HTTP_USER_AGENT

### ISSUE THREAD

**Issue by MillerSp** [opencartbrasil/opencartbrasil#48]
Olá, Após a atualização da loja para ultima versao esta aparecendo o seguinte erro

24-06-2020 22:19:51 - PHP Notice:  Undefined index: HTTP_USER_AGENT no arquivo /home3/brindqoo/public_html/system/storage/modification/catalog/controller/common/menu.php na linha 5

Tentei ver se teria relação com as modificações mas minhas modificações nenhuma trabalha relacionada ao menu.php da pasta controler...

Não sei reproduzir o erro e nem de onde poderia estar vindo, mas me parece ser algo com a parte mobile

**Comment by v5mvidal** [comment]
Este erro não é causado pela atualização do OpenCart Brasil, mas sim por alguma modificação que você instalou na sua loja.

A prova está no caminho do arquivo com erro que está dentro da pasta modification, ou seja, de modificações:
system/storage/**modification**/catalog/controller/common/menu.php

Além de não haver o trecho de código na linha citada.

Espero ter ajudado.
