### ISSUE TITLE
[bug] E-mails Sendpulse não funciona na versão Brasil

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#50]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.4.15

**Que parte da loja é afetada pelo erro?**
todos e-mails

**Faça um resumo do problema ocasionado pelo erro:**
não envia e-mails usando SENDPULSE - [https://sendpulse.com/br/prices/smtp](url)
na versão internacional o envio do e-mail pelo sendpulse funciona normalmente.

outros serviços de e-mail sendgrid, mailgun funcionam na versão brasil e internacional.

**Link para imagens com capturas da tela de erro:**
Como está configurado abaixo. Esta mesma configuração funciona normalmente na versão internacional.
Caso seja preciso que eu passe login e senha, posso passar no privado.
Mas o serviço é gratuito no sendpulse, basta cadastrar que terá 12 mil e-mails transacionais.

![1](https://user-images.githubusercontent.com/37814975/87965959-90b06b80-ca8a-11ea-9e37-96f9888f266d.jpg)

**Comment by v5mvidal** [comment]
Corrigido:
https://github.com/opencartbrasil/opencartbrasil/commit/8afa0ce769015c5bc250536e60b786fcfba53d9d

**Comment by rlasmar** [comment]
Olá @v5mvidal 

Atualizei para versão 1.5, porém continua sem funcionar o sendpulse.
Nenhum erro do log. Dentro do painel do sendpulse nem chega a descontar os e-mails, portanto o serviço nem chega a ser acionado.

Na versão internacional do Opencart funciona o sendpulse.

Você chegou a testar o uso do sendpulse?

**Comment by v5mvidal** [comment]
@rlasmar vou verificar novamente, **mas a versão nacional está utilizando exatamente a mesma lib de envio da versão internacional**, por isso de imediato não sei o que pode está causando o problema.

**Comment by v5mvidal** [comment]
Resolvido.
