### ISSUE TITLE
[bug] Produtos relacionados ficam linkados após duplicar produto

### ISSUE THREAD

**Issue by MillerSp** [opencartbrasil/opencartbrasil#54]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.3 versao 1.4.15

**Que parte da loja é afetada pelo erro?**
Produtos relacionados

**Faça um resumo do problema ocasionado pelo erro:**
Quando voce duplica um PRODUTO AZUL, e depois renomeia para PRODUTO ROSA  e depois nos relacionados do PRODUTO ROSA você coloca algum item, esse item auto incrementa ao PRODUTO AZUL

Dessa forma todos os produtos duplicados vão interagir, e depois os produtos iniciais vão acumular uma quantidade enorme de produtos relacionados indesejaveis....

Isso acontece ja desde a primeira versa 3.x 

**Link para imagens com capturas da tela de erro:**
https://brindesbarato.com.br/produto-relacionados-bug.jpg

**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

 - Você está em um computador local ou hospedagem web?
 
 - Se estiver em uma hospedagem web, qual hospedagem?
 br.Bluehost.com
 - Qual o sistema operacional utilizado?
 linux
 - Qual o servidor web utilizado?
 apache
 - Qual o servidor de banco dados utilizado?
 msqli
 - Qual a versão do PHP?
 5.6
 - Se aplicável, qual o(s) navegador(es) utilizado(s) [por exemplo: chrome 75]:
 
 - Se aplicável, informe detalhes do dispositivo móvel utilizado:

**Comment by v5mvidal** [comment]
Não se trata de um bug, mas de um comportamento padrão do OpenCart que também copia os produtos relacionados quando você realiza a cópia do produto.

Você pode remover o recurso comentando a linha:
`//$data['product_related'] = $this->getProductRelated($product_id);`

No arquivo:
admin/model/catalog/**product.php**
