### ISSUE TITLE
[bug] Número da fatura não aparece

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#55]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.4.15

**Que parte da loja é afetada pelo erro?**
Admin - Pedido - Gerar fatura

**Faça um resumo do problema ocasionado pelo erro:**
O número da fatura não está aparecendo

**Link para imagens com capturas da tela de erro:**
![1](https://user-images.githubusercontent.com/37814975/90283664-8c376280-de3e-11ea-8062-fe8059efccb0.JPG)

**Comment by v5mvidal** [comment]
Se não há fatura gerada, então não será exibido o **Fatura #**
