### ISSUE TITLE
[bug] Opencart 3.0.3.7 - Gerenciador de arquivos de imagens não atualiza após adicionar imagens

### ISSUE THREAD

**Issue by AMS-2017** [opencartbrasil/opencartbrasil#56]
**Em que versão do OpenCart Brasil o erro ocorre?**
3.0.3.7
**Que parte da loja é afetada pelo erro?**
Gerenciador de arquivos de imagens no cadastro dos produtos e também o botão atualizar modificações não funciona.
**Faça um resumo do problema ocasionado pelo erro:**
Um dos erros seria o Gerenciador de arquivos de imagens, quando eu crio uma pasta ou envio fotos elas não aparecem na hora. Aí eu limpo o cache do navegador e entro novamente no site, somente nesta hora é que o site atualiza e aparece a pasta e as imagens. O mesmo ocorre se eu excluir imagens, elas não somem. Então, novamente eu preciso limpar o histórico do chome (cache) e entrar novamente no site para ver as modificações. O botão "Atualizar" das modificações também não funciona. Quando eu instalo alguma extensão ela não atualiza e se eu tento excluir ela também não exclui, somente se eu acessar via FTP e fizer a exclusão do arquivo ou pasta.
**Link para imagens com capturas da tela de erro:**
https://prnt.sc/yzwuj3
https://prnt.sc/yzugv1
**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

 - Você está em um computador local ou hospedagem web?
 Hospedagem web
 - Se estiver em uma hospedagem web, qual hospedagem?
 Hostgator
 - Qual o sistema operacional utilizado?
hospedagem Linux, meu computador Windows 10
 - Qual o servidor web utilizado?
 VPS
 - Qual o servidor de banco dados utilizado?
 MySQL
 - Qual a versão do PHP?
 PHP: 7.3.6
 - Se aplicável, qual o(s) navegador(es) utilizado(s) [por exemplo: chrome 75]:
 Chrome
 - Se aplicável, informe detalhes do dispositivo móvel utilizado:

**Comment by valdeir-v5** [comment]
Testamos na versão 3.0.3.7 e funcionou como esperado.
