### ISSUE TITLE
 Procedimento de segurança

### ISSUE THREAD

**Issue by wubuyun** [opencartbrasil/opencartbrasil#6]
Procedimento de segurança
 É muito importante que você mova a pasta storage para fora do diretório público (public_html, www ou htdocs por exemplo), de modo que ela não seja acessível pela web.
 
devo e como fazer ?

**Comment by v5manoel** [comment]
Selecione a opção "Mover automaticamente", e clique no botão "**Mover**".

**Comment by wubuyun** [comment]
![capturar](https://user-images.githubusercontent.com/35350235/49097474-f156b900-f253-11e8-820d-0f66d04e89aa.JPG)

**Comment by v5manoel** [comment]
A mensagem de erro informa que o diretório (pasta) para onde está sendo movido o diretório **storage** não tem permissão de escrita, que no padrão é 755.

Se você não sabe como resolver, solicite ajuda ao suporte para sua hospedagem.
