### ISSUE TITLE
[Sugestão] Adicionar lazyload nativo suportado por padrão pelos navegadores

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#60]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.5.1

**Que parte da loja é afetada pelo erro?**
Front-end

**Faça um resumo do problema ocasionado pelo erro:**
Desde 2020 a maioria dos navegadores (chrome, firefox, edge) suporta o lazyload nativamente, basta adicionar o código loading="lazy" em todas as chamadas de códigos que tenha imagens

Exemplo: `<div class="image"><a href="{{ product.href }}"><img src="{{ product.thumb }}" loading="lazy" alt="{{ product.name }}" title="{{ product.name }}" class="img-responsive" /></a></div>`

**Comment by rlasmar** [comment]
@v5mvidal atualizei para versão 1.6 beta 1, mas os arquivos estão desatualizados.
Verifiquei que as modificações foram feitas apenas no template basico, esqueceu do template default.

O mesmo vale para a sugestão de remover o cdn do cloudflare da outra sugestão.

**Comment by v5mvidal** [comment]
@rlasmar agradeço pelo feedback!

Vamos providenciar agora mesmo os ajustes, pois o objetivo ao lançar a versão 1.6 beta 1 era testar as rotinas automatizadas e executar o controle de qualidade das novas funcionalidades e correções antes de lançar a versão final.

**Comment by v5mvidal** [comment]
Correções acrescentadas na release 1.6-beta.2
