### ISSUE TITLE
[Sugestão] Alterar link cloudflare fontawesome e atualizar fontawsome.min.css para incluir font-style

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#61]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.5.1

**Que parte da loja é afetada pelo erro?**

Front-End.

**Faça um resumo do problema ocasionado pelo erro:**
1. Particularmente, depois que foi adicionado no header.twig para obter alguns arquivos do cdn cloudflare, o score de desempenho do pagespeed do google cai um pouco, devido ao cloudflare apresentar maior latência (não sei porque, já que deveria ser o contrário).

Quando troco para obter os arquivos diretamente do meu servidor, tenho melhor desempenho, segundo o pagespeed.

```
<link href="catalog/view/javascript/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<script src="catalog/view/javascript/jquery/2.2.4/jquery.min.js"></script>

```
2. No teste de pagespeed, é recomendado: "Garanta que o texto continue visível durante o carregamento da webfont"
Isto pode ser resolvido alterando o arquivo font-awesome.min.css e adicionando o código: **font-display: swap**, conforme mostra o link [https://web.dev/font-display/?utm_source=lighthouse&utm_medium=unknown](url), porém o arquivo teria que ser servido diretamente do servidor da loja, ao invés do cdn do cloudflare, visto que o arquivo do cloudflare não tem o font-display.

E na url de fonts do google api do header.twig, pode ser alterada para:
`https://fonts.googleapis.com/css?family=Open+Sans:400,400i,300,700&display=swap`
Ao obter essa url com o final swap, o arquivo já contém o font-display: swap

**Comment by rlasmar** [comment]
@v5mvidal verifiquei que o fontawsome.min.css não incluíram o font-display: swap

arquivo: catalog/view/javascript/font-awesome/css/font-awesome.min.css

**Comment by v5mvidal** [comment]
Neste caso, se utilizarmos o arquivo:
catalog/view/javascript/font-awesome/css/font-awesome.css

Não teremos problema com desempenho?

Aguardo feedback.

**Comment by rlasmar** [comment]
Creio que não. Eu coloquei o font-display: swap e não tive alteração de desempenho. Além de ajustar para as recomendações do google e melhorar a nota no pagespeed.

**Comment by v5mvidal** [comment]
@rlasmar perfeito!

Vamos incluir na próxima versão.
