### ISSUE TITLE
Sem acesso ao admin

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#68]
**Em que versão do OpenCart Brasil o erro ocorre?**

1.6

**Que parte da loja é afetada pelo erro?**

admin

**Faça um resumo do problema ocasionado pelo erro:**

Você excedeu o limite de tentativas de acesso. Por segurança, tente acessar novamente após 1 hora ou redefina sua senha.

**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

Provavelmente alguém tentando acessar o admin e agora estou sem acesso ao admin.

Como resolver isso?

**Comment by rlasmar** [comment]
Também não consigo redefinir senha, pois tá desabilitado no admin.

**Comment by v5mvidal** [comment]
Só para eu entender o contexto do problema.

Você está utilizando um usuário padrão tipo 'admin'?

Estou pensando sobre qual a melhor estratégia para lidar com isso, pois aumentar a segurança da administração tem sido uma de nossas prioridades.

**Comment by rlasmar** [comment]
sim, usuario admin

**Comment by rlasmar** [comment]
Tem como resetar a senha direto no banco de dados?
pois provavelmente vou ficar sem acesso ao admin, deve ser bot tentando acessar.... e vai ser o dia todo isso

**Comment by rlasmar** [comment]
Ou desabilitar essa trava de tentativa de login direto no código do opencart.

**Comment by v5mvidal** [comment]
Para resolver especificadamente seu problema, acesse a tabela "***_user**" em seu banco de dados e no cadastro do usuário "**admin**", mude o nome do usuário na coluna "**username**" e salve uma senha em md5 no campo "**password**".

Para converter a senha em um hash md5, você pode utilizar um site como:
https://www.md5hashgenerator.com/

**Importante:** Utilize uma senha aleatória quando for gerar o hash md5, e depois de acessar a administração altere novamente para uma senha que seja segura. Lembrando que o OpenCart converterá após o primeiro acesso do usuário a senha de hash md5 para um hash mais seguro.

**Comment by rlasmar** [comment]
Obrigado, acesso restaurado.

Agora como posso desabilitar temporariamente essa trava no código?
Certamente algum bot deve ficar tentando acessar de madrugada e pela manhã fico sem acesso.

**Comment by v5mvidal** [comment]
Utilize um nome de usuário que não seja fácil de identificar por bots, pode ser um nome composto, pois funciona sem problemas para logar na administração do OpenCart, sendo que isso já inutilizará o bot.

Vou trabalhar para incluir uma opção para desabilitar o limite de tentativas de login nas configurações da loja e já lançar na próxima versão de correção do OpenCart Brasil, que deverá ser a 1.6.1, mas vou aguardar pelo menos 3 dias para verificar se mais algum bug será relatado em relação a versão 1.6.0 para incluir a correção nessa nova versão.

Na versão 1.7.0 devemos incluir mais um fator de segurança no login.

**Comment by v5mvidal** [comment]
Utilize um nome de usuário que não seja fácil de identificar por bots, pode ser um nome composto, pois funciona sem problemas para logar na administração do OpenCart, sendo que isso já inutilizará o bot.

Vamos trabalhar para incluir uma opção para desabilitar o limite de tentativas de login nas configurações da loja e já lançar na próxima versão de correção do OpenCart Brasil, que deverá ser a 1.6.1, mas vamos aguardar pelo menos 3 dias para verificar se mais algum bug será relatado em relação a versão 1.6.0 para incluir a correção nessa nova versão.

Na versão 1.7.0 devemos incluir mais um fator de segurança no login.

**Comment by v5mvidal** [comment]
Na versão 1.6.1 adicionamos nas configurações da loja uma opção para configurar a quantidade de tentativas de login na administração.
