### ISSUE TITLE
Sidebar com tamanho errado (administrador)

### ISSUE THREAD

**Issue by Racass** [opencartbrasil/opencartbrasil#7]
Versão: 3.0.3.1

Descrição:
Na área de administração do opencart, o painel vertical esquerdo fica com as letras para fora do painel.
Resolução da tela: 1366x768 e 1024x768. em ambas ocorrem.
Navegador: firefox

**Para reproduzir o erro**
Se aplicável, descreva os passos para reproduzir o erro:
Vá em dominio.com.br/admin
entre com usuario e senhassss

**Capturas de tela / gravações de tela**
![image](https://user-images.githubusercontent.com/31106782/51047671-3b9bbb80-15b0-11e9-8ff0-6fde9099923c.png)

**Ambiente de trabalho (preencha as seguintes informações):**
 -  Computador local - Notebook
 -  Windows 10
 -  Apache: 2.4.37
 -  MySQL: 5.6.41-84.1
 -  PHP: 7.0.33
 -  Firefox 64.0.2

**Observação importante**

No Google chrome funciona normalmente. Issue acontece apenas no navegador FIREFOX

**Comment by v5manoel** [comment]
Olá @Racass 

Agradeço por detalhar o problema, pois assim fica mais fácil de ajudar. :)

Você ou quem dá suporte para a sua loja, instalou uma modificação na loja para recolher o sidebar igual ao efeito que há nas versões 2 do OpenCart, sendo que está modificação é que está causando o problema.

Em resumo, esse problema está sendo causado por alguma modificação instalada em sua loja, que talvez funcionava e deixou de funcionar na versão 3.0.3.1, por causa de uma atualização que foi feita no sidebar do OpenCart 3.0.3.1

Espero ter ajudado. :)

**Comment by Racass** [comment]
Olá!

@v5manoel, esse erro na sidebar foi encontrado após a instalação do open cart desse repositóro. Ainda não instalei nenhuma extensão. Foi encontrado logo na instalação limpa em um servidor hospedado na hostgator.

Irei desativar/reativar as extensões e te digo se causa alguma diferença!
Reportei pois não encontrei o mesmo erro na versão 3.0 instalada pelo softacalous.

Obrigado,

**Comment by v5manoel** [comment]
Perfeito! Aguardo seu feedback. :)
