### ISSUE TITLE
[bug] Não envia e-mail utilizando SMTP da Amazon SES

### ISSUE THREAD

**Issue by MarcosLealDev** [opencartbrasil/opencartbrasil#74]
**Em que versão do OpenCart Brasil o erro ocorre?**
Versão 3.0.3.3 (Brasil 1.6.1)

**Que parte da loja é afetada pelo erro?**
Admin em geral.  A versão inglês 3.0.3.2 funciona sem problemas.

**Faça um resumo do problema ocasionado pelo erro:**
Vendas > Pedidos e entrando em um dos pedidos, adicionando um comentário, selecionando notificar cliente e clicando histório ... e nenhum email é enviado.

**Link para imagens com capturas da tela de erro:**
Nenhum erro é gerado no log da loja, nem no arquivo storage/logs/mail.log, nem no log do php.

**Responda as perguntas abaixo sobre o seu ambiente de trabalho:**

 - Você está em um computador local ou hospedagem web?
hospedagem web

 - Se estiver em uma hospedagem web, qual hospedagem?
 DigitalOcean
 
 - Qual a versão do PHP?
 PHP 7.3.30

**Comment by valdeirpsr** [comment]
Olá!

O erro foi corrigido no commit 490736c737df4664cde61c07353b61a94deb9399

**Comment by MarcosLealDev** [comment]
Olá, Valdeir,

Infelizmente tenho testado com o $this->from (em vez do $this->smtp_username) mas ainda não envia nenhum email.
E não consigo encontrar nenhum log que acusa o problema.

Aqui vai o meu código copiado e colado só pra ter certeza que eu não fiz nenhum erro:
Linhas 155 até 161
```
                        if ($this->verp) {
                                fputs($handle, 'MAIL FROM: <' . $this->from . '>XVERP' . "\r\n");
                        } else {
                                fputs($handle, 'MAIL FROM: <' . $this->from . '>' . "\r\n");
                        }

                        $this->handleReply($handle, 250, 'Erro: O servidor SMTP recusou o e-mail do remetente!');

**Comment by valdeirpsr** [comment]
@MarcosLealDev, fiz um teste e funcionou.

O fato de não haver mensagens de erros, pode ser que o armazenamento ou exibição deles tenha sido desabilitada. Verifique na página de configuração da loja (System > Settings).

Usei as seguintes configurações:

| Key | Value |
| ----- | -------- |
| Host | tls://\<SERVER-ID\>.\<REGION\>.amazonaws.com |
| User | --- |
| Password | --- |
| Port | 587 | 

**Observação**

O envio vai funcionar corretamente ao enviar notificações de pedidos por e-mail, mas não vai funcionar no formulário de contato (nem na versão internacional, nem na versão BR).

**Comment by v5mvidal** [comment]
Acrescentando, na Digital Ocean em alguns caso é necessário solicitar o desbloqueio da porta **587** para poder enviar e-mail por SMTP, pois a porta pode está bloqueada.

Na Amazon SES, se o domínio da loja não estiver registrado dentro do serviço Amazon SES e a conta for Sandbox, você não irá conseguir enviar e-mail, lembrando que se o domínio estiver registrado e já estiver em produção no Amazon SES, pode ser necessário utilizar um e-mail de remetente que pertença ao domínio registrado na Amazon SES, caso contrário também não vai funcionar.

Espero ter ajudado.

**Comment by MarcosLealDev** [comment]
Tenho no mesmo host (DigitalOcean) um outro domain com Opencart em inglês versão 3.0.3.2 e os emails funcionam com o AWS SES sem problemas.

Sim, os domains estão registrados e em produção.

O email funciona tanto com ssl na porta 465 como tls na porta 587.

Rodando ufw status no terminal eu tenho a lista das portas abertas e inclui no final :
587                        ALLOW       Anywhere
465                        ALLOW       Anywhere
587 (v6)                   ALLOW       Anywhere (v6)
465 (v6)                   ALLOW       Anywhere (v6)

Configurações > Gerenciar Lojas > E-mail
![email_alerta](https://user-images.githubusercontent.com/14096346/134010768-9d1cf122-5ba0-44fe-8846-485128e7dcb3.png)

Tudo começou quando troquei da versão 2.1.0.2 para a versão Opecart 3.0.3.3 Brasil 1.6.1

O email do meu formulário de contato funciona porque uso o tema Journal 3.

Estou tentando com um outro email server e também não está funcionando. E continuo não conseguindo ver nada nos logs.
