### ISSUE TITLE
Atualização de dados

### ISSUE THREAD

**Issue by diegospm** [opencartbrasil/opencartbrasil#8]
Olá Manoel,

Não é um problema e antes de enviar um pull no repo gostaria de entender o motivo....

Não entendo o porque do OC não utilizar a query UPDATE na atualização de dados, principalmente dos produtos.

Por exemplo, no produto:

Deleta os dados atuais (do meu ponto de vista perde tempo e é desnecessário)
$this->db->query("DELETE FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");

Insere os novos dados
foreach ($data['product_description'] as $language_id => $value) {
$this->db->query("INSERT INTO " . DB_PREFIX . "product_description SET product_id = '" . (int)$product_id . "', language_id = '" . (int)$language_id . "', name = '" . $this->db->escape($value['name']) . "', description = '" . $this->db->escape($value['description']) . "', tag = '" . $this->db->escape($value['tag']) . "', meta_title = '" . $this->db->escape($value['meta_title']) . "', meta_description = '" . $this->db->escape($value['meta_description']) . "', meta_keyword = '" . $this->db->escape($value['meta_keyword']) . "'");
}

**Poderia ser assim:**
//$this->db->query("DELETE FROM " . DB_PREFIX . "product_description WHERE product_id = '" . (int)$product_id . "'");

Atualiza os dados, uma execução a menos....
foreach ($data['product_description'] as $language_id => $value) {
$this->db->query("UPDATE " . DB_PREFIX . "product_description SET language_id = '" . (int)$language_id . "', name = '" . $this->db->escape($value['name']) . "', description = '" . $this->db->escape($value['description']) . "', tag = '" . $this->db->escape($value['tag']) . "', meta_title = '" . $this->db->escape($value['meta_title']) . "', meta_description = '" . $this->db->escape($value['meta_description']) . "', meta_keyword = '" . $this->db->escape($value['meta_keyword']) . "' WHERE product_id = '" . (int)$product_id . "'");
}

A não ser que eu esteja enganado, mas da forma atual deve ser mais lento e também deve consumir um pouco mais de recuso, ainda que seja irrisório...

Isso ocorre com outros dados nos arquivos model...

**Comment by v5manoel** [comment]
Concordo que é um procedimento no mínimo estranho, mas por questões de compatibilidade com a versão internacional do OpenCart, por enquanto não alterei estruturas do model, exceto aquelas que estavam visivelmente com problemas, como no sistema de afiliados e outras.

**Comment by diegospm** [comment]
Sim, concordo que não é legal modificar a estrutura até por questão de atualizações futuras que a plataforma irá receber.

Sei que demanda tempo, mas acho que esse problema poderia ser resolvido adicionando um evento antes da função edit, claro, se isso for valer à pena.

Vou postar um pull aqui, o mesmo que postei no repo internacional onde abordo a questão de repetição no código. Entendo que a intenção do Daniel foi tornar o nível de aprendizagem muito alto na plataforma e eu aprendi a programar graças a Deus (de forma autodidata) e ao OC (extremamente fácil mesmo de aprender), mas acho que já está na hora deles reduzirem as repetições desnecessárias e nem precisa de refatorar com novas classes, basta aplicar a abordagem OOP nas classes existentes (controllers e models) para reduzir drasticamente o tamanho do código....
