### ISSUE TITLE
Erro ao atualizar para versão 1.3

### ISSUE THREAD

**Issue by SuporteWD** [opencartbrasil/opencartbrasil#9]
Ao tentar atualizar aparece o seguinte erro: 

![Screenshot_1](https://user-images.githubusercontent.com/43239651/56038349-14b46900-5d08-11e9-8435-e740ba76c660.jpg)

**Comment by v5manoel** [comment]
Olá @SuporteWD 

O tópico no fórum abaixo, explica como resolver o problema. =)
https://forum.opencartbrasil.com.br/viewtopic.php?f=76&t=18136
