### ISSUE TITLE
[bug] Erro durante atualização para 1.7

### ISSUE THREAD

**Issue by rlasmar** [opencartbrasil/opencartbrasil#94]
**Em que versão do OpenCart Brasil o erro ocorre?**
1.7

**Que parte da loja é afetada pelo erro?**
Durante atualização

**Faça um resumo do problema ocasionado pelo erro:**

Baixando a última versão...
Extraindo os arquivos...
Copiando os arquivos...
Atualizando o banco de dados...
SyntaxError: Unexpected token W in JSON at position 0
parsererror
Warning: Use of undefined constant DIR_WEBHOOK - assumed 'DIR_WEBHOOK' (this will throw an Error in a future version of PHP) no arquivo /home/admin/web/www.dominio.com/public_html/system/engine/actionhook.php na linha 30

 
 - Qual a versão do PHP?
7.3

**Comment by v5mvidal** [comment]
Acabei de atualizar a versão 1.7.0 com a correção do bug.

Para corrigir manualmente, você pode substituir o código do arquivo abaixo:
admin/controller/tool/**update.php**

Pela versão corrigida abaixo:
https://raw.githubusercontent.com/opencartbrasil/opencartbrasil/main/admin/controller/tool/update.php

E qualquer novo problema, é só avisar.

**Comment by v5mvidal** [comment]
Durante a atualização automática da versão não está atualizando os arquivos config.php por isso o erro.

O problema está em sua hospedagem, onde você deve mudar as configurações de "open_basedir" para "none" (nenhum) ou vazio.

Assim o problema durante a atualização não vai mais ocorrer.

Poderia verificar?

Aguardamos retorno.

**Comment by rlasmar** [comment]
@v5mvidal Alterei o base_dir para none.

![1](https://user-images.githubusercontent.com/37814975/138380676-30050881-4460-4b41-bfb9-2a402d7caba4.PNG)

Como você havia alterado meu arquivo config.php e inserido o define do webhook, a loja tava funcionando.
Eu removi a linha do webhook config.php e tentei novamente atualizar a loja para simular o erro.
Mesmo com o **open_basedir none** continou dando o mesmo erro, ou seja, não conseguiu modificar o arquivo config.php.
![2](https://user-images.githubusercontent.com/37814975/138380924-ad197e85-af71-406e-8693-65d374e6a26b.PNG)

O que mais poderia estar impedindo a atualização desse arquivo?

@valdeir-v5 estou fazendo apenas a atualização automática pelo painel.
